version: '3.8'

services:
  resource-rabbitmq:
    image: rabbitmq:3.11-management
    restart: "no"
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - resource-network
networks:
  resource-network:
    external:
      name: resource-network
